# Generated by Django 3.2.3 on 2021-07-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
